# Generated by Django 5.1.3 on 2024-11-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'More Blogs'},
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default='hello world'),
        ),
    ]
